{% set version = "6.2.0.20260408" %}

package:
  name: types-cachetools
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-cachetools/types_cachetools-{{ version }}.tar.gz
  sha256: 0d8ae2dd5ba0b4cfe6a55c34396dd0415f1be07d0033d84781cdc4ed9c2ebc6b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/cachetools-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for cachetools
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
