schema_version: 1

context:
  version: "7.0.0.20260503"

package:
  name: types-cachetools
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-cachetools/types_cachetools-${{ version }}.tar.gz
  sha256: dfa4dcdf453f397dfc6d69fc0a57423ac1f248393f70aa56b5d05fac2df7a96c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - urllib3 >=2

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
  - package_contents:
      site_packages:
        - cachetools-stubs/__init__.pyi

about:
  summary: Typing stubs for cachetools
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed
  repository: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
